GET http://localhost:3001/users


###

POST  http://localhost:3001/register
Content-Type: application/json

{
    "username": "x", 
    "email" : "x@gamil.com",
    "password": "x"
}




###

POST  http://localhost:3001/login
Content-Type: application/json
withCredentials: true
Accept: "application/json"

{
    "username": "wendy", 
    "password": "password"
}

###

POST  http://localhost:3001/login
Content-Type: application/json

{
    "username": "x", 
    "password": "x"
}